---
- name: Add Tier 0 Redundant Link to Core Routers
  community.vmware.vmware_guest_network:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ item }}"
    label: eth3
    network_name: "CDX - Tier 0 - Internet"
    connected: true
  with_items:
    - "{{ core_rtr_1 }}"
    - "{{ core_rtr_2 }}"
    - "{{ core_rtr_3 }}"