---
- name: Initialize VSphere Environment
  hosts: localhost
  become: false
  gather_facts: true
  pre_tasks:
    - include_vars: global_vars.yml
    - include_vars: vcenter_vars.yml
  roles:
    - vsphere_init

- name: Deploy CDX-E Internet Routing Infrastructure
  hosts: localhost
  become: false
  gather_facts: true
  pre_tasks:
    - include_vars: global_vars.yml
    - include_vars: vcenter_vars.yml
  roles:
    - deploy_routers

- name: Deploy CDX-E Internet Services
  hosts: localhost
  become: false
  gather_facts: true
  pre_tasks:
    - include_vars: global_vars.yml
    - include_vars: vcenter_vars.yml
  roles:
    - deploy_services