---
# Variables for the routers role

core_rtr_1: CORE-T0-R1
core_rtr_2: CORE-T0-R2
core_rtr_3: CORE-T0-R3
tier_1_rtr_ams: IXP-EQIX-2
tier_1_rtr_syd: IXP-EQIX-3
tier_1_rtr_sea: IXP-EQIX-4
tier_1_rtr_tor: IXP-EQIX-5
tier_1_rtr_de: IXP-EQIX-6
tier_1_rtr_vlv: IXP-EQIX-7
tier_1_rtr_dxb: IXP-EQIX-8
tier_1_rtr_br: IXP-EQIX-9
tier_1_rtr_icn: IXP-EQIX-10
tier_1_rtr_lon: IXP-EQIX-11