---
- name: Create Internet Web Server
  import_tasks: ../common/tasks/terraform_clone_vm.yml  
  vars:
    # terraform_folder_var: "{{ internet_path_terraform }}/vm/web"
    terraform_folder_var: "./roles/web_deploy/tf"
    task_title: "Internet Web Server"

- name: Wait For {{ vm }} To Be Available
  import_tasks: ../common/tasks/wait_for_vm_tools.yml    # Wait for System To Be Available

- name: Set Time Zone to Pacific Standard Time
  import_tasks: ../common/tasks/win_configure_time_zone.yml    # Set to Pacific Standard Time

- name: Apply Server Configuration To {{ vm }}
  import_tasks: win_configure_server.yml    # Apply Server Configuration

- name: Shut Down {{ vm }}
  import_tasks: ../common/tasks/win_shut_down_vm.yml    # Shut Down System

- name: Wait for {{ vm }} to shut down
  import_tasks: ../common/tasks/wait_for_vm_poweroff.yml    # Wait For Shut Down

- name: Power On {{ vm }}
  import_tasks: ../common/tasks/power_on_vm.yml    # Power On System
