---
- name: Add DNS Zone Configuration to Powershell script
  import_tasks: win_add_dns_zones_to_pwsh_script.yml    # Add DNS record data to DNS Configuration Powershell script

- name: Add DNS Records Configuration to Powershell script
  import_tasks: win_add_dns_records_to_pwsh_script.yml    # Add DNS record data to DNS Configuration Powershell script

- name: Set Firewall Profile to Public
  import_tasks: win_add_fw_profile_to_nstp_config.yml    # Set Firewall Profile to Public

- name: Configure Windows Firewall Rules
  import_tasks: win_add_fw_rules_to_nstp_config.yml    # Configure Firewall Rule - Allow ICMP and NTP

- name: Disable IPv6
  import_tasks: ../common/tasks/win_disable_ipv6.yml    # Disable IPv6

- name: Set IP Address and DNS information
  import_tasks: ../common/tasks/win_configure_network_interface.yml    # Set IP Address and DNS information

- name: Set Additional IP addresses
  import_tasks: win_establish_additional_ip_addresses.yml    # Set Additional IP addresses

- name: Set W32time Service Startup Type to Automatic
  import_tasks: ../common/tasks/win_set_service_automatic_startup.yml    # Set w32time service startup type to automatic
  vars:
    win_svc: "W32Time"

- name: Set up NTP Service
  import_tasks: win_set_up_ntp_svc.yml    # Set up NTP Service

- name: Update NTP Service
  import_tasks: win_update_ntp_svc.yml    # Update NTP Service

- name: Start W32Time Service
  import_tasks: ../common/tasks/win_start_svc.yml    # Start w32time service
  vars:
    win_svc: "W32Time"

- name: Rename Server to {{ vm }}
  import_tasks: ../common/tasks/win_rename_system.yml    # Rename System