---
# - name: Configure W32Time for {{ vm }} - Set up NTP Service
#   community.vmware.vmware_vm_shell:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: "{{ vcenter_validate_certs }}"
#     datacenter: "{{ vcenter_datacenter }}"
#     vm_id: "{{ vm }}"
#     vm_username: "{{ win_admin }}"
#     vm_password: "{{ win_admin_password }}"
#     vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
#     vm_shell_args: '-ExecutionPolicy Bypass -command "Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpServer -Name \"Enabled\" -Value 1; Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\W32Time\Config -name \"AnnounceFlags\" -value 5"'
#     wait_for_process: true

- name: Set up NTP Service
  ansible.builtin.lineinfile:
    path: "{{ server_config }}"
    line: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpServer -Name "Enabled" -Value 1; Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\W32Time\Config -name "AnnounceFlags" -value 5
    create: yes