---
# - name: Configure Network Interface for {{ vm }} - Establish Additional IP Addresses
#   community.vmware.vmware_vm_shell:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: "{{ vcenter_validate_certs }}"
#     datacenter: "{{ vcenter_datacenter }}"
#     vm_id: "{{ vm }}"
#     vm_username: "{{ win_admin }}"
#     vm_password: "{{ win_admin_password }}"
#     vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
#     vm_shell_args: '-ExecutionPolicy Bypass -command "New-NetIPAddress -IPAddress {{ item.ip }} -PrefixLength {{ item.mask_length }} -DefaultGateway {{ item.gateway }} -InterfaceAlias Ethernet0 -SkipAsSource $true"'
#     wait_for_process: false
#   loop:
#     - { ip: 198.41.0.4, mask_length: 24, gateway: 198.41.0.18 }
#     - { ip: 199.9.14.201, mask_length: 24, gateway: 199.9.14.25 }
#     - { ip: 192.33.4.12, mask_length: 24, gateway: 192.33.4.79 }
#     - { ip: 199.7.91.13, mask_length: 24, gateway: 199.7.91.4 }
#     - { ip: 192.203.230.10, mask_length: 24, gateway: 192.203.230.102 }
#     - { ip: 192.5.5.241, mask_length: 24, gateway: 192.5.5.210 }
#     - { ip: 192.112.36.4, mask_length: 24, gateway: 192.112.36.97 }
#     - { ip: 198.97.190.53, mask_length: 24, gateway: 198.97.190.84 }
#     - { ip: 192.36.148.17, mask_length: 24, gateway: 192.36.148.47 }
#     - { ip: 192.58.128.30, mask_length: 24, gateway: 192.58.128.76 }
#     - { ip: 193.0.14.129, mask_length: 24, gateway: 193.0.14.81 }
#     - { ip: 199.7.83.42, mask_length: 24, gateway: 199.7.83.92 }
#     - { ip: 202.12.27.33, mask_length: 24, gateway: 202.12.27.116 }

- name: Set Additional IP addresses
  ansible.builtin.lineinfile:
    path: "{{ server_config }}"
    line: New-NetIPAddress -IPAddress {{ item.ip }} -PrefixLength {{ item.mask_length }} -InterfaceAlias Ethernet0 -SkipAsSource $true
    create: yes
  loop:
    - { ip: 198.41.0.4, mask_length: 24, gateway: 198.41.0.18 }
    - { ip: 199.9.14.201, mask_length: 24, gateway: 199.9.14.25 }
    - { ip: 192.33.4.12, mask_length: 24, gateway: 192.33.4.79 }
    - { ip: 199.7.91.13, mask_length: 24, gateway: 199.7.91.4 }
    - { ip: 192.203.230.10, mask_length: 24, gateway: 192.203.230.102 }
    - { ip: 192.5.5.241, mask_length: 24, gateway: 192.5.5.210 }
    - { ip: 192.112.36.4, mask_length: 24, gateway: 192.112.36.97 }
    - { ip: 198.97.190.53, mask_length: 24, gateway: 198.97.190.84 }
    - { ip: 192.36.148.17, mask_length: 24, gateway: 192.36.148.47 }
    - { ip: 192.58.128.30, mask_length: 24, gateway: 192.58.128.76 }
    - { ip: 193.0.14.129, mask_length: 24, gateway: 193.0.14.81 }
    - { ip: 199.7.83.42, mask_length: 24, gateway: 199.7.83.92 }
    - { ip: 202.12.27.33, mask_length: 24, gateway: 202.12.27.116 }