---
- name: Add NICs to {{ core_rtr_1 }}
  community.vmware.vmware_guest_network:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ core_rtr_1 }}"
    state: "{{ item.state }}"
    network_name: "{{ item.network_name | default(omit) }}"
    connected: true
  loop:
    - { label: eth0, network_name: "Range Operations", state: present }
    - { label: eth1, network_name: "CDX - Tier 1 - Americas", state: present }
    - { label: eth2, network_name: "CDX - Tier 0 - Internet", state: present }