---
- name: Create Core Routers
  import_tasks: clone_vyos.yml

- name: Add NICs to CORE-T0-R1
  import_tasks: add_nic_to_core-t0-r1.yml

- name: Add NICs to CORE-T0-R2
  import_tasks: add_nic_to_core-t0-r2.yml

- name: Add NICs to CORE-T0-R3
  import_tasks: add_nic_to_core-t0-r3.yml

- name: Add Tier 0 Redundant Link to Core Routers
  import_tasks: add_redundant_tier_0_link.yml

- name: Power On Core Routers
  import_tasks: power_on_routers.yml

- name: Wait for Core Routers to be available
  import_tasks: wait_for_router_power_on.yml

- name: Wait 15 seconds before continuing
  import_tasks: ../common/tasks/wait_for_n_seconds.yml
  vars:
    seconds: 15

- name: Configure {{ core_rtr_1 }}
  import_tasks: ../common/tasks/configure_vyos_router.yml
  vars:
    vm: "{{ core_rtr_1 }}"
    vyos_configuration: "{{ core_rtr_1_config }}"

- name: Configure {{ core_rtr_2 }}
  import_tasks: ../common/tasks/configure_vyos_router.yml
  vars:
    vm: "{{ core_rtr_2 }}"
    vyos_configuration: "{{ core_rtr_2_config }}"

- name: Configure {{ core_rtr_3 }}
  import_tasks: ../common/tasks/configure_vyos_router.yml
  vars:
    vm: "{{ core_rtr_3 }}"
    vyos_configuration: "{{ core_rtr_3_config }}"