---
- name: Wait for Core Routers to be available
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ item }}"
    timeout: 120
  delegate_to: localhost
  with_items:
    - "{{ core_rtr_1 }}"
    - "{{ core_rtr_2 }}"
    - "{{ core_rtr_3 }}"