---
- name: Set Firewall Profile to Public
  import_tasks: win_add_fw_profile_to_web_config.yml    # Set Firewall Profile to Public

- name: Configure Windows Firewall Rules
  import_tasks: win_add_fw_rules_to_web_config.yml    # Configure Firewall Rules

- name: Disable IPv6
  import_tasks: ../common/tasks/win_disable_ipv6.yml    # Disable IPv6

- name: Set IP Address and DNS information
  import_tasks: ../common/tasks/win_configure_network_interface.yml    # Set IP Address and DNS information

- name: Establish Additional IP Gateways
  import_tasks: win_establish_additional_gateways.yml    # Establish Additional IP Gateways

- name: Set Additional IP addresses
  import_tasks: win_establish_additional_ip_addresses.yml    # Set Additional IP addresses

- name: Set W32time Service Startup Type to Automatic
  import_tasks: ../common/tasks/win_set_service_automatic_startup.yml    # Set w32time service startup type to automatic
  vars:
    win_svc: "W32Time"

- name: Start W32Time Service
  import_tasks: ../common/tasks/win_start_svc.yml    # Start w32time service
  vars:
    win_svc: "W32Time"

- name: Prepare Web Content Disk
  import_tasks: win_provision_disk.yml    # Prepare Web Content Disk

- name: Add msftconnecttest and NCSI site data
  import_tasks: win_add_msftconnecttest_and_ncsi_data.yml    # Add msftconnecttest and NCSI site data

- name: Install Microsoft IIS on {{ vm }}
  import_tasks: ../common/tasks/win_windows_feature_install.yml    # Install Microsoft IIS

- name: Configure Websites in Microsoft IIS on {{ vm }}
  import_tasks: win_configure_websites.yml    # Install Websites (msftconnecttest and NCSI)

- name: Rename Server to {{ vm }}
  import_tasks: ../common/tasks/win_rename_system.yml    # Rename System