---
# - name: Configure Network Interface for {{ vm }} - Set Additional IP addresses
#   community.vmware.vmware_vm_shell:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: "{{ vcenter_validate_certs }}"
#     datacenter: "{{ vcenter_datacenter }}"
#     vm_id: "{{ vm }}"
#     vm_username: "{{ win_admin }}"
#     vm_password: "{{ win_admin_password }}"
#     vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
#     vm_shell_args: '-ExecutionPolicy Bypass -command "New-NetIPAddress -IPAddress {{ item.ip }} -PrefixLength {{ item.mask_length }} -InterfaceAlias Ethernet0 -SkipAsSource $true"'
#     wait_for_process: false
#   loop:
#     - { ip: 104.100.233.170, mask_length: 8 }
#     - { ip: 104.100.234.69, mask_length: 8 }
#     - { ip: 104.72.48.87, mask_length: 8 }
#     - { ip: 143.84.78.18, mask_length: 16 }
#     - { ip: 143.84.99.20, mask_length: 16 }
#     - { ip: 156.112.106.15, mask_length: 16 }
#     - { ip: 156.112.108.76, mask_length: 16 }
#     - { ip: 172.226.176.220, mask_length: 16 }
#     - { ip: 172.226.181.65, mask_length: 16 }
#     - { ip: 23.204.70.60, mask_length: 16 }
#     - { ip: 23.204.166.21, mask_length: 16 }
#     - { ip: 23.211.39.103, mask_length: 16 }
#     - { ip: 23.211.93.125, mask_length: 16 }
#     - { ip: 23.211.18.40, mask_length: 16 }
#     - { ip: 23.214.39.160, mask_length: 16 }
#     - { ip: 23.214.40.141, mask_length: 16 }
#     - { ip: 23.214.42.140, mask_length: 16 }
#     - { ip: 204.79.197.203, mask_length: 24 }

- name: Set Additional IP addresses
  ansible.builtin.lineinfile:
    path: "{{ server_config }}"
    line: New-NetIPAddress -IPAddress {{ item.ip }} -PrefixLength {{ item.mask_length }} -InterfaceAlias Ethernet0 -SkipAsSource $true
    create: yes
  loop:
    - { ip: 23.96.0.45, mask_length: 24 }
    - { ip: 104.100.233.170, mask_length: 8 }
    - { ip: 104.100.234.69, mask_length: 8 }
    - { ip: 104.72.48.87, mask_length: 8 }
    - { ip: 143.84.78.18, mask_length: 16 }
    - { ip: 143.84.99.20, mask_length: 16 }
    - { ip: 156.112.106.15, mask_length: 16 }
    - { ip: 156.112.108.76, mask_length: 16 }
    - { ip: 172.226.176.220, mask_length: 16 }
    - { ip: 172.226.181.65, mask_length: 16 }
    - { ip: 23.204.70.60, mask_length: 16 }
    - { ip: 23.204.166.21, mask_length: 16 }
    - { ip: 23.211.39.103, mask_length: 16 }
    - { ip: 23.211.93.125, mask_length: 16 }
    - { ip: 23.211.18.40, mask_length: 16 }
    - { ip: 23.214.39.160, mask_length: 16 }
    - { ip: 23.214.40.141, mask_length: 16 }
    - { ip: 23.214.42.140, mask_length: 16 }
    - { ip: 204.79.197.203, mask_length: 24 }