---
# - name: Configure Network Interface for {{ vm }} - Establish Additional IP Gateways
#   community.vmware.vmware_vm_shell:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: "{{ vcenter_validate_certs }}"
#     datacenter: "{{ vcenter_datacenter }}"
#     vm_id: "{{ vm }}"
#     vm_username: "{{ win_admin }}"
#     vm_password: "{{ win_admin_password }}"
#     vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
#     vm_shell_args: '-ExecutionPolicy Bypass -command "New-NetIPAddress -IPAddress {{ item.ip }} -PrefixLength {{ item.mask_length }} -DefaultGateway {{ item.gateway }} -InterfaceAlias Ethernet0 -SkipAsSource $true"'
#     wait_for_process: false
#   loop:
#     - { ip: 104.100.226.218, mask_length: 8, gateway: 104.0.0.49 }
#     - { ip: 143.84.78.18, mask_length: 16, gateway: 143.84.2.5 }
#     - { ip: 156.112.106.15, mask_length: 16, gateway: 156.112.87.4 }
#     - { ip: 172.226.176.220, mask_length: 16, gateway: 172.226.117.84 }
#     - { ip: 23.204.166.21, mask_length: 16, gateway: 23.204.107.102 }
#     - { ip: 23.211.39.103, mask_length: 16, gateway: 23.211.39.2 }
#     - { ip: 23.214.39.160, mask_length: 16, gateway: 23.214.0.71 }
#     - { ip: 13.33.255.55, mask_length: 24, gateway: 13.33.255.4 }
#     - { ip: 132.163.4.223, mask_length: 24, gateway: 132.163.4.5 }
#     - { ip: 136.160.88.139, mask_length: 24, gateway: 136.160.88.95 }
#     - { ip: 15.72.178.23, mask_length: 24, gateway: 15.72.178.100 }
#     - { ip: 151.101.1.67, mask_length: 24, gateway: 151.101.1.49 }
#     - { ip: 172.217.12.4, mask_length: 24, gateway: 172.217.12.79 }
#     - { ip: 172.232.3.42, mask_length: 24, gateway: 172.232.3.174 }
#     - { ip: 184.25.206.43, mask_length: 24, gateway: 184.25.206.124 }
#     - { ip: 184.31.198.51, mask_length: 24, gateway: 184.31.198.242 }
#     - { ip: 185.199.111.153, mask_length: 24, gateway: 185.199.111.89 }
#     - { ip: 192.124.249.10, mask_length: 24, gateway: 192.124.249.109 }
#     - { ip: 192.124.249.3, mask_length: 24, gateway: 192.124.249.109 }
#     - { ip: 204.79.197.200, mask_length: 24, gateway: 204.79.197.8 }
#     - { ip: 208.80.153.224, mask_length: 24, gateway: 208.80.153.1 }
#     - { ip: 214.3.16.180, mask_length: 24, gateway: 214.3.16.81 }
#     - { ip: 23.11.216.158, mask_length: 24, gateway: 23.11.216.55 }
#     - { ip: 23.208.159.201, mask_length: 24, gateway: 23.208.159.25 }
#     - { ip: 23.213.54.35, mask_length: 24, gateway: 23.213.54.117 }
#     - { ip: 3.212.51.88, mask_length: 24, gateway: 3.212.51.177 }
#     - { ip: 52.222.30.169, mask_length: 24, gateway: 52.222.30.244 }
#     - { ip: 52.61.85.77, mask_length: 24, gateway: 52.61.85.9 }
#     - { ip: 96.127.62.6, mask_length: 24, gateway: 96.127.62.74 }
#     - { ip: 98.138.219.231, mask_length: 24, gateway: 98.138.219.46 }
#     - { ip: 13.107.4.52, mask_length: 24, gateway: 13.107.4.113 }
#     - { ip: 172.232.4.139, mask_length: 24, gateway: 172.232.4.27 }
#     - { ip: 104.17.33.82, mask_length: 24, gateway: 104.17.33.125 }

- name: Establish Additional IP Gateways
  ansible.builtin.lineinfile:
    path: "{{ server_config }}"
    line: New-NetIPAddress -IPAddress {{ item.ip }} -PrefixLength {{ item.mask_length }} -DefaultGateway {{ item.gateway }} -InterfaceAlias Ethernet0 -SkipAsSource $true
    create: yes
  loop:
    - { ip: 104.100.226.218, mask_length: 8, gateway: 104.0.0.49 }
    - { ip: 143.84.78.18, mask_length: 16, gateway: 143.84.2.5 }
    - { ip: 156.112.106.15, mask_length: 16, gateway: 156.112.87.4 }
    - { ip: 172.226.176.220, mask_length: 16, gateway: 172.226.117.84 }
    - { ip: 23.204.166.21, mask_length: 16, gateway: 23.204.107.102 }
    - { ip: 23.211.39.103, mask_length: 16, gateway: 23.211.39.2 }
    - { ip: 23.214.39.160, mask_length: 16, gateway: 23.214.0.71 }
    - { ip: 13.33.255.55, mask_length: 24, gateway: 13.33.255.4 }
    - { ip: 132.163.4.223, mask_length: 24, gateway: 132.163.4.5 }
    - { ip: 136.160.88.139, mask_length: 24, gateway: 136.160.88.95 }
    - { ip: 15.72.178.23, mask_length: 24, gateway: 15.72.178.100 }
    - { ip: 151.101.1.67, mask_length: 24, gateway: 151.101.1.49 }
    - { ip: 172.217.12.4, mask_length: 24, gateway: 172.217.12.79 }
    - { ip: 172.232.3.42, mask_length: 24, gateway: 172.232.3.174 }
    - { ip: 184.25.206.43, mask_length: 24, gateway: 184.25.206.124 }
    - { ip: 184.31.198.51, mask_length: 24, gateway: 184.31.198.242 }
    - { ip: 185.199.111.153, mask_length: 24, gateway: 185.199.111.89 }
    - { ip: 192.124.249.10, mask_length: 24, gateway: 192.124.249.109 }
    - { ip: 192.124.249.3, mask_length: 24, gateway: 192.124.249.109 }
    - { ip: 204.79.197.200, mask_length: 24, gateway: 204.79.197.8 }
    - { ip: 208.80.153.224, mask_length: 24, gateway: 208.80.153.1 }
    - { ip: 214.3.16.180, mask_length: 24, gateway: 214.3.16.81 }
    - { ip: 23.11.216.158, mask_length: 24, gateway: 23.11.216.55 }
    - { ip: 23.208.159.201, mask_length: 24, gateway: 23.208.159.25 }
    - { ip: 23.213.54.35, mask_length: 24, gateway: 23.213.54.117 }
    - { ip: 3.212.51.88, mask_length: 24, gateway: 3.212.51.177 }
    - { ip: 52.222.30.169, mask_length: 24, gateway: 52.222.30.244 }
    - { ip: 52.61.85.77, mask_length: 24, gateway: 52.61.85.9 }
    - { ip: 96.127.62.6, mask_length: 24, gateway: 96.127.62.74 }
    - { ip: 98.138.219.231, mask_length: 24, gateway: 98.138.219.46 }
    - { ip: 13.107.4.52, mask_length: 24, gateway: 13.107.4.113 }
    - { ip: 172.232.4.139, mask_length: 24, gateway: 172.232.4.27 }
    - { ip: 104.17.33.82, mask_length: 24, gateway: 104.17.33.125 }