---
# - name: Configure Network Interface for {{ vm }} - Set IP Address and DNS information
#   community.vmware.vmware_vm_shell:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: "{{ vcenter_validate_certs }}"
#     datacenter: "{{ vcenter_datacenter }}"
#     vm_id: "{{ vm }}"
#     vm_username: "{{ win_admin }}"
#     vm_password: "{{ win_admin_password }}"
#     vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
#     vm_shell_args: '-ExecutionPolicy Bypass -command "New-NetIPAddress -IPAddress {{ ip }} -PrefixLength {{ subnet_mask_length }} -InterfaceAlias {{ ethernet_alias }} -DefaultGateway {{ gateway }}; Set-DnsClientServerAddress -InterfaceAlias {{ ethernet_alias }} -ServerAddresses {{ dns_server }}"'
#     wait_for_process: true

- name: Set IP Address and DNS information
  ansible.builtin.lineinfile:
    path: "{{ server_config }}"
    line: New-NetIPAddress -IPAddress {{ item.ip }} -PrefixLength {{ item.mask_length }} -InterfaceAlias {{ item.interface_alias }} -DefaultGateway {{ item.default_gateway }}; Set-DnsClientServerAddress -InterfaceAlias {{ item.interface_alias }} -ServerAddresses {{ item.dns }}
    create: yes
  loop:
    - { ip: "{{ ip }}", mask_length: "{{ subnet_mask_length }}", interface_alias: "{{ ethernet_alias }}", default_gateway: "{{ gateway }}", dns: "{{ dns_server }}"}