---
- name: Initialize Terraform Environment
  import_tasks: ../common/tasks/terraform_init.yml    # 'terraform init''
  vars:
    terraform_folder_var: "{{ terraform_root }}"

- name: Apply Terraform Configuration
  import_tasks: ../common/tasks/terraform_apply_module.yml    # 'terraform apply''
  vars:
    terraform_folder_var: "{{ terraform_root }}"
    task_title: "Provisioning VSphere Networks and VCenter Folders Environment"
    module: environment

