---
- name: Connect KMS Host to CDX-E Network
  community.vmware.vmware_guest_network:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: cdx-docker.cdx.lab
    mac_address: 00:50:56:9d:a3:5b
    network_name: "CDX - Tier 2 - Seattle"
    state: present