---
- name: Disconnect Repositories from CDX-E Network
  community.vmware.vmware_guest_network:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ item.name }}"
    mac_address: "{{ item.mac }}"
    network_name: "CDX Staging"
    state: present
  loop:
    - { name: cdx-sus-01.cdx.lab, mac: 00:0c:29:ec:65:53 }
    - { name: yum-mirror, mac: 00:50:56:9d:ae:8e }
    - { name: apt-mirror, mac: 00:50:56:9d:ae:8e }